### ISSUE TITLE
Doesn't seem to work in R studio on Win 7 -  Error in file(con, "r") 

### ISSUE THREAD

**Issue by hpiedcoq** [hpiedcoq/mailbox-with-R#1]
```
 Error in file(con, "r") : cannot open the connection In addition: Warning message:
In file(con, "r") :
  cannot open file
```
I suspect a pathfile issue with Windows' crappy ability to handle spaces and strange charachers in directory names.

**Comment by krlplm** [comment]
Hi. Thanks for developing such a nice r script to analyze eml files. I faced the similar issue loading eml files passing the directory.

**Configure the path as below which works. Notice the \\(double-slash) and /(single-slash)**

`C:\\Users\\cyberdude\\Documents\\R\\mailbox-with-R-master\\mailbox-with-R-master/mails/`

**Comment by hpiedcoq** [comment]
Hi @krlplm!

Thank you for you hint!!
I'll add this info to the readme file.
